### ISSUE TITLE
Postfix   error log

### ISSUE THREAD

**Issue by Tulskie** [shoujii/Next-Server-Bookworm#10]
Hallo Marcel,
nach dem ich mal meine Logfiles durchgesehen habe, ist mir aufgefallen das sehr viele Einträge mit einem unknown user kvminstall@mail.pipmatz.de dabei sind.
Bsp: Feb  6 02:55:02 mail postfix/local[38917]: 599AA101696: to=<kvminstall@mail.pipmatz.de>, orig_to=<root>, relay=local, delay=0.62, delays=0.6/0.01/0/0.01, dsn=5.1.1, status=bounced (unknown user: "kvminstall")

Bekommt man die irgendwie noch weg?
Gruß Ralf

**Comment by shoujii** [comment]
Hallo Ralf,

ich vermute, dass da ein Bot versucht Server nach einem bestimmten Nutzer abzuklappern.

In dem Fall nach einem bestimmten Setup das den genannten Nutzer als Standard hat?

Könntest du mir einen längeren Log Ausschnitt zur Verfügung stellen?

Gruß Marcel

**Comment by Tulskie** [comment]
Hallo Marcel,
anbei ein größerer Auszug aus der mail.log und mail.info.
[Mail_logs.txt](https://github.com/shoujii/Next-Server-Bullseye/files/8051870/Mail_logs.txt)

Gruß Ralf

**Comment by shoujii** [comment]
Hallo Ralf,

ich bin jetzt leider nur kurz dazu gekommen auf das Log zu schauen.

Für mich sieht es danach aus, dass ein paar Bots versuchen den Mailserver auf bestimmte Adressen abzuscannen.

Es werden Emails an gewisse Email Accounts geschickt (kvminstall), die es bei dir natürlich nicht gibt und der Mailserver packt die in die Warteschlabge und antwortet nach einer Zeit das es den Account nicht gibt.

Manche Anfragen sortiert er direkt aus, weil der Hostname und die IP der Anfrage nicht übereinstimmen.

Für das erste würde ich das als „normal“ ansehen.

SSH Zugänge werden auch sehr gut am Tag „gescannt“ auf Standard Zugänge.

Ich werde aber mal schauen Fail2ban zu optimieren, dann kann der vielleicht auch ein paar Anfragen aussortieren.

Gruß Marcel

**Comment by BoBBer446** [comment]
Was willst du den aussortieren? 
Due "Fehler" von @Tulskie sind außerhalb des eigenen Zugriffs. Am ende ist das System nicht unsicher oder sicherer durch das aussortieren ins Nirvana. 

Die Logs zeigen kein akutes Problem. Eine Lösung wäre nur dev > 0 und das ist keine Lösung sondern "Magie" :D 
Ich würde es genau so lassen.

**Comment by shoujii** [comment]
Ja, es sieht eher nach normalen "abscannen" aus, aber nicht genug Versuchen, um da dauerhaft etwas zu bannen.
Der Mailserver lehnt die Verbindungen ja eh schon ab, weil die reversed Auflösung etc nicht passen :)
