### ISSUE TITLE
Composer root

### ISSUE THREAD

**Issue by shoujii** [shoujii/Next-Server-Bookworm#2]
Do not run Composer as root/super user! See https://getcomposer.org/root for details
Continue as root/super user [yes]? yes

needs to be fixed

**Comment by shoujii** [comment]
is now running without user action.

-> changing to none root account needed in the future

**Comment by Tulskie** [comment]
![image](https://user-images.githubusercontent.com/46045752/151681466-871bf739-43d7-4d3f-a9ec-edc3e2a2a38e.png)

Da stimmt auch noch etwas nicht.

**Comment by shoujii** [comment]
Den Fehler konnte ich leider nicht nachvollziehen :/

Bei mir läuft pma durch.
Hattest du vor dem Fehler schon ein anderes Addon installiert?
![Bildschirmfoto von 2022-01-31 09-23-34](https://user-images.githubusercontent.com/20255426/151761178-7189fa7b-d045-4dd0-bcc1-89b95657374d.png)

**Comment by Tulskie** [comment]
Die Installation hat diesen Fehler gemeldet.
pma war aber soweit wie ich das einschätzen kann i.O.
Start, Anmeldung lief problemlos, Tabellen waren auch alle vorhanden.

**Comment by shoujii** [comment]
Ich habe nochmal geschaut:
Die selben Hinweise habe ich auch bei der Installation, aber es scheint kein "Problem" zu sein.

Siehe Fehlermeldungen bei PHPmyadmin selbst:

https://github.com/phpmyadmin/phpmyadmin/issues/14513
und https://github.com/phpmyadmin/phpmyadmin/issues/13374
